#! /usr/bin/python3
import numpy as np
from ReadFile import Read

def ParticleInfo(filename, prtclType, prtclNum):
    '''
    '''
    time, numprtcls, data = Read(filename)
    requestedPrtcl = np.where(data["type"] == prtclType)[prtclNum - 1]
    print(requestedPrtcl)

if __name__ == "__main__":
    ParticleInfo("MW_000.txt", 1, 2)